{% set name = "vaex-viz" %}
{% set version = "0.6.0" %}
{% set sha256 = "ea13bea18da84b4f5d17e47f43a33b7939e2242b18f6df33154da2f4de21ecda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core >=4.7.0,<5
    - matplotlib-base >=1.3.1
    - pillow

test:
  imports:
    - vaex.viz

about:
  home: https://www.github.com/vaexio/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Visualization for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
    - JovanVeljanoski
