{% set name = "vaex-viz" %}
{% set version = "0.3.1" %}
{% set sha256 = "d1e9ab6daec0d4cf81d97cf991c42333aebd231bd0c273988dcb40b2bdf6a322" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core
    - matplotlib >=1.3.1
    - pillow

test:
  imports:
    - vaex.viz

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Visualization for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
