{% set name = "vaex-viz" %}
{% set version = "0.5.4" %}
{% set sha256 = "1b3b0b9cccc6c3590f191c674d5b6e03cb9790dea7e9a40a826d61ecc7aacc38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core >=4.7.0,<5
    - matplotlib-base >=1.3.1
    - pillow

test:
  imports:
    - vaex.viz

about:
  home: https://www.github.com/vaexio/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Visualization for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
